export const TOAST_ERROR = 'TOAST_ERROR'
export const TOAST_SUCCESS = 'TOAST_SUCCESS'
export const TOAST_NOTI = 'TOAST_NOTI'
export const TYPE_FILE = 'TYPE_FILE'
export const TYPE_FONT = 'TYPE_FONT'
export const TYPE_IMAGE = 'TYPE_IMAGE'
export const DEFAULT_NEW_FOLDER_NAME = 'New Folder'
export const UNKNOWN_FILE_TYPE = 'Unknown'
